### PR TITLE
Make 'graph.svg' and 'graph_disabled.svg' themed icons.

### PR DESCRIPTION
**Pull request by weisJ**
Make 'graph.svg' and 'graph_disabled.svg' themed icons:
- Icons that are loaded as `themed=true` should also be themeable icons.

Ignore IntelliJ project files:
- Eclipse project files are already ignored. This does the same for IntelliJ project files.

Avoid unnecessarily keeping the loading indicator running:
- Even if the indicator isn't visible setting it's running state to `true` will result in a running background timer.

### CODE REVIEW

**Comment by weisJ** [comment]
I have also simplified the color definitions of all other icons.

**Comment by GraxCode** [comment]
This somehow broke the icon loader: `com.kitfox.svg.SVGException: java.lang.IllegalArgumentException: User must specify at least 2 colors`

**Comment by weisJ** [comment]
What is the complete stacktrace?

**Comment by GraxCode** [comment]
```java
java.lang.IllegalArgumentException: User must specify at least 2 colors

	at java.awt.MultipleGradientPaint.<init>(MultipleGradientPaint.java:169)
	at java.awt.LinearGradientPaint.<init>(LinearGradientPaint.java:286)
	at com.kitfox.svg.LinearGradient.getPaint(LinearGradient.java:157)
	at com.kitfox.svg.ShapeElement.renderShape(ShapeElement.java:167)
	... 84 more

```

**Comment by GraxCode** [comment]
```java
java.lang.IllegalArgumentException: User must specify at least 2 colors

	at com.kitfox.svg.Path.render(Path.java:94)
	at com.kitfox.svg.Group.render(Group.java:205)
	at com.kitfox.svg.SVGRoot.render(SVGRoot.java:335)
	at com.kitfox.svg.SVGRoot.renderToViewport(SVGRoot.java:266)
	at com.kitfox.svg.SVGDiagram.render(SVGDiagram.java:111)
	at com.kitfox.svg.app.beans.SVGIcon.paintIcon(SVGIcon.java:322)
```

**Comment by weisJ** [comment]
Can you print `getSvgURI().toASCIIString()` for the `SVGIcon` that throws the exception?

**Comment by GraxCode** [comment]
This happens while loading the tree. I'm pretty sure it is the package icon, as jar files with no packages work.

**Comment by weisJ** [comment]
Replace
````java
pack = Utils.getIcon("package.svg");
````
with
````
pack = Utils.getIcon("package.svg", true);
````
in `ClassTreeCellRenderer:22`

**Comment by GraxCode** [comment]
It works now, thanks. Will write if something else is not working.

**Pull request merged**
