### PR TITLE
Add support for file drag and drops

### PR DESCRIPTION
**Pull request by x4e**
Allows dragging and dropping jars onto the GUI to import classes

### CODE REVIEW

**Comment by GraxCode** [comment]
Doesn't threadtear already support file drag and drop?

**Comment by x4e** [comment]
It didn't when I wrote the PR. 
At least by that I mean dragging a jar onto the main window did not result in any action.
And there are no instances of `DropTarget` in the code.
So I don't think it does?

**Comment by x4e** [comment]
Accidentally closed

**Comment by GraxCode** [comment]
What OS are you on? It works for me on Windows 10 and Manjaro Linux.

**Comment by x4e** [comment]
Apologies, it seems it does work. Not sure what went wrong last time I tried.

**Pull request closed without merging**
